//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Note {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Note.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while saving the file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AnErrorOccurredWhileSavingTheFile_ {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileSavingTheFile.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change BackGround Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBackGroundColor {
            get {
                return ResourceManager.GetString("ChangeBackGroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeColor {
            get {
                return ResourceManager.GetString("ChangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decrease Font Size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DecreaseFontSize {
            get {
                return ResourceManager.GetString("DecreaseFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Reading File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Increase Font Size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IncreaseFontSize {
            get {
                return ResourceManager.GetString("IncreaseFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Italic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There must be at least one note.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ThereMustBeAtLeastOneNote {
            get {
                return ResourceManager.GetString("msg_ThereMustBeAtLeastOneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open (Ctrl + O)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Text File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenTextFile {
            get {
                return ResourceManager.GetString("OpenTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseEnterAvalue_ {
            get {
                return ResourceManager.GetString("PleaseEnterAvalue.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RenameNote {
            get {
                return ResourceManager.GetString("RenameNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save (Ctrl + S)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As (Ctrl + Shift + S)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SaveAs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveAsText {
            get {
                return ResourceManager.GetString("SaveAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveCompleted {
            get {
                return ResourceManager.GetString("SaveCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TextFiles {
            get {
                return ResourceManager.GetString("TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file has been saved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TheFileHasBeenSaved_ {
            get {
                return ResourceManager.GetString("TheFileHasBeenSaved.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no content to save.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ThereIsNoContentToSave_ {
            get {
                return ResourceManager.GetString("ThereIsNoContentToSave.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnderLine과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnderLine {
            get {
                return ResourceManager.GetString("UnderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Untitled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
    }
}
